version: '3.8'
services:
  web:
    container_name: natutrends_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - node_modules:/app/node_modules
      - .:/app

volumes:
  node_modules:
